# ReactiveTransactionsTest
After passing tests throws exceptions related to PostgreSQL connection, it don't affect tests, i don't know the cause of the problem yet
